### ISSUE TITLE
About test images

### ISSUE THREAD

**Issue by dushide** [zzs1994/D-LADMM#1]
Thank you for your excellent research work，I have some questions to ask about test images.
Written in your article :
‘’and compare their results on both synthetic datasets and natural images‘’.
How to generate the lena_pepper_01.mat file in your article?
I want to test my data with your algorithm.
Can you provide a link to the program or related dataset that generated the test image?
Looking forward to your reply.
Sincerely

**Comment by XingyuXie** [comment]
@dushide
1. Actually, for natural images (real datasets), we train our model in an unsupervised way. To generate the dictionary matrix, we use the patch dictionary method _(Xu & Yin, 2014)_ to learn a 256 × 512 dictionary A.

2. I guess you mean the training data, since no test data. The training data is just coming from cropping the original **noised** natural images. Each cropped patch is a training instance.

3. Note that, the duality-gap-related function we released in the code is only for the sparse recovery problem. The new optimization problem needs to reconstruct the corresponding duality-gap-function or its approximation.

4. For more information, my Wechat:  156-516-700-27 (delete ‘-’).

    _Xu Y, Yin W. A fast patch-dictionary method for whole image recovery[J]. arXiv preprint arXiv:1408.3740, 2014._

**Comment by dushide** [comment]
Thank you for your reply, I mean that I saw “img_data = sio.loadmat('lena_pepper_01.mat')” in your code. 
I want to try to run the program with other pictures. (Such as Barb Boat France Frog Goldhill Lena Library Mandrill Mountain Peppers Washsat Zelda in your paper.)
How to get the .mat file for these images？
Is the code in this paper  (Xu & Yin, 2014) a way to generate these .mat files?
But I didn't find the code for it.
I just want to test more examples to see the effect of the algorithm.
I look forward to your reply again.
Sincerely
